name: hidden_pass
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  http: 1.3.0
  dart_jsonwebtoken: ^2.9.0
  english_words: ^4.0.0
  provider: ^6.1.2
  url_launcher: ^6.0.20
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
