name: hidden_pass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Onest
      fonts:
        - asset: lib/UI/UTILS/FONTS/Onest-Regular.ttf
        - asset: lib/UI/UTILS/FONTS/Onest-Bold.ttf
          weight: 700
        - asset: lib/UI/UTILS/FONTS/Onest-ExtraBold.ttf
          weight: 900
  uses-material-design: true
